apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: web
  - port: 4040
    name: spark
  selector:
    app: {{ template "zeppelin.name" . }}
    release: {{ .Release.Name }}
